### ISSUE TITLE
EOFError: Ran out of input (verze 3.10)

### ISSUE THREAD

**Issue by AggressiveCombo** [setnicka/ulozto-downloader#113]
File:           Agent v sukni 1 2000 Cz Full HD digitálne remastrované.mkv
URL:            https://uloz.to/file/1mIiFsbJsU6l/agent-v-sukni-1-2000-cz-full-hd-digitalne-remastrovane-mkv#!ZGywZQR2Awt1MGZlZQIuATV5BGqyL2j2IKZ0AGMHMmW2pQR2LD==
Download type:  CAPTCHA protected download
[Part 0]        Waiting for CAPTCHA...
[Part 1]        Waiting for CAPTCHA...
[Part 2]        Waiting for CAPTCHA...
[Part 3]        Waiting for CAPTCHA...
[Part 4]        Waiting for CAPTCHA...
[Part 5]        Waiting for CAPTCHA...
[Part 6]        Waiting for CAPTCHA...
[Part 7]        Waiting for CAPTCHA...
[Part 8]        Waiting for CAPTCHA...
[Part 9]        Waiting for CAPTCHA...
[Part 10]       Waiting for CAPTCHA...
[Part 11]       Waiting for CAPTCHA...
[Part 12]       Waiting for CAPTCHA...
[Part 13]       Waiting for CAPTCHA...
[Part 14]       Waiting for CAPTCHA...
[Part 15]       Waiting for CAPTCHA...
[Part 16]       Waiting for CAPTCHA...
[Part 17]       Waiting for CAPTCHA...
[Part 18]       Waiting for CAPTCHA...
[Part 19]       Waiting for CAPTCHA...Traceback (most recent call last):
  File "C:\Users\Aggressive_Combo\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Aggressive_Combo\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Aggressive_Combo\AppData\Local\Programs\Python\Python310\Scripts\ulozto-downloader.exe\__main__.py", line 7, in <module>
  File "C:\Users\Aggressive_Combo\AppData\Local\Programs\Python\Python310\lib\site-packages\uldlib\cmd.py", line 44, in run
    d.download(args.url, args.parts, args.output)
  File "C:\Users\Aggressive_Combo\AppData\Local\Programs\Python\Python310\lib\site-packages\uldlib\downloader.py", line 306, in download
    self.captcha_process.start()
  File "C:\Users\Aggressive_Combo\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Aggressive_Combo\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Aggressive_Combo\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "C:\Users\Aggressive_Combo\AppData\Local\Programs\Python\Python310\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Aggressive_Combo\AppData\Local\Programs\Python\Python310\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'weakref.ReferenceType' object
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Aggressive_Combo\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
[Progress]       0.00 MB (0.00 %)       avg. speed: 0.00 MB/s   curr. speed: 0.00 MB/s  remaining: 0:00:00
ain
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by AggressiveCombo** [comment]
Pouzil fix od #91

**Comment by Vojtak42** [comment]
`pip install --upgrade ulozto-downloader`

**Comment by setnicka** [comment]
Closing this, should be fixed for Windows in new versions.
