### ISSUE TITLE
log_func parameter missing

### ISSUE THREAD

**Issue by SpiReCZ** [setnicka/ulozto-downloader#127]
There is a log_func parameter missing with recent changes:
```
Traceback (most recent call last):
  File "/home/spire/git/ulozto-streamer/ulozto-downloader.py", line 7, in <module>
    cmd.run()
  File "/home/spire/git/ulozto-streamer/uldlib/cmd.py", line 82, in run
    tor.launch(solver.log)
TypeError: launch() takes 1 positional argument but 2 were given
```
I am not sure if it was removed by mistake or if there was other intention, so leaving it with you to fix @setnicka .

**Comment by setnicka** [comment]
I accidentally pushed commits before everything was completed. It should be fixed now.
