### ISSUE TITLE
[Errno 24] Too many open files when downloading bunch of files in one command

### ISSUE THREAD

**Issue by pschonmann** [setnicka/ulozto-downloader#143]
Pustil jsem si 19x Download s 75x konexema - URLs za sebou. Pri 12tem downloadu to takhle chiplo

Download type:	CAPTCHA protected download
Size / parts: 	1269.75MB => 75 x 16.93MB
[Link solve]	All downloads started, no need to solve another CAPTCHAs…
		[Ok: 53 / 59] :( [Badcp: 5 Limited: 0 Censored: 0 NetErr: 1]
[Progress]	1252.82 MB (98.67 %)	avg. speed: 4.36 MB/s	curr. speed: 0.29 MB/s	remaining: 0:00:04
[STATUS]	Download in progress
Traceback (most recent call last):
  File "/home/pschonmann/.local/lib/python3.10/site-packages/stem/connection.py", line 1103, in _read_cookie
OSError: [Errno 24] Too many open files: '/home/pschonmann/Stažené/ULOZ/tor_data_dir_683bc316-8abf-4687-9ea2-1b02d58141fc/control_auth_cookie'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 953, in run
  File "/home/pschonmann/SynologyDrive/apps/_LINUX/ulozto-downloader/uldlib/downloader.py", line 96, in _captcha_breaker
  File "/home/pschonmann/SynologyDrive/apps/_LINUX/ulozto-downloader/uldlib/page.py", line 232, in captcha_download_links_generator
  File "/home/pschonmann/SynologyDrive/apps/_LINUX/ulozto-downloader/uldlib/torrunner.py", line 90, in reload
  File "/home/pschonmann/.local/lib/python3.10/site-packages/stem/control.py", line 1112, in authenticate
  File "/home/pschonmann/.local/lib/python3.10/site-packages/stem/connection.py", line 629, in authenticate
  File "/home/pschonmann/.local/lib/python3.10/site-packages/stem/connection.py", line 591, in authenticate
  File "/home/pschonmann/.local/lib/python3.10/site-packages/stem/connection.py", line 904, in authenticate_safecookie
  File "/home/pschonmann/.local/lib/python3.10/site-packages/stem/connection.py", line 1107, in _read_cookie
stem.connection.UnreadableCookieFile: Authentication failed: unable to read '/home/pschonmann/Stažené/ULOZ/tor_data_dir_683bc316-8abf-4687-9ea2-1b02d58141fc/control_auth_cookie' ([Errno 24] Too many open files: '/home/pschonmann/Stažené/ULOZ/tor_data_dir_683bc316-8abf-4687-9ea2-1b02d58141fc/control_auth_cookie')

**Comment by setnicka** [comment]
To naráží na limit počtu otevřených souborů vynucovaný systémem. Často bývá nastavený na 1024 (vypíše to příkaz `ulimit -n`). Pravděpodobně mezi navazujícími stahováními ulozto-downloader nazavře všechny otevřené file handlery.

Pokusím se na tento problém co nejdříve podívat.

**Comment by setnicka** [comment]
Mělo by být snad vyřešeno ve verzi 3.4.1, která merguje #151, kde je několik oprav a zlepšení okolo Toru.
