### ISSUE TITLE
WTF is that url?! HELP...

### ISSUE THREAD

**Issue by cqeta1564** [setnicka/ulozto-downloader#154]
EN: Hi, I am trying to install and use this downloader in Windows. After several attempts I finally ran the script and got an error which makes sense. I can't have "https" in the address twice in a row. (see one of the last lines) What, why and how!

CZ: Ahoj, snažím se nainstalovat a používat tento downloader ve Windows. Po několika pokusech jsem konečně spustil skript a dostal jsem chybu která dává smysl. Nemůžu mít v adrese dvakrát za sebou "https". (viz jeden z posleních řádků) Co, proč a jak?!

Code here/kód zde:

C:\Users\blablabla>ulozto-downloader "https://uloz.to/file/blablabla"
Starting downloading for url 'https://uloz.to/file/blablabla'
Getting info (filename, filesize, ...)
CAPTCHA protected download - CAPTCHA challenges will be displayed

Starting TOR...
←[34m[Link solve]       ←[0mNew TOR session for POST captcha :) [Ok: ←[32m0←[0m / ←[34m0←[0m] :( [Badcp: ←[31m0←[0m Limited: ←[31m0←[0m Censored: ←[31m0←[0m Traceback (most recent call last):URL obtained, trying to solve←[K
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\blablabla\AppData\Local\Programs\Python\Python311\Scripts\ulozto-downloader.exe\__main__.py", line 7, in <module>
  File "C:\Users\blablabla\AppData\Local\Programs\Python\Python311\Lib\site-packages\uldlib\cmd.py", line 44, in run
    d.download(args.url, args.parts, args.output)
  File "C:\Users\blablabla\AppData\Local\Programs\Python\Python311\Lib\site-packages\uldlib\downloader.py", line 237, in download
    download_url = next(self.captcha_download_links_generator)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\blablabla\AppData\Local\Programs\Python\Python311\Lib\site-packages\uldlib\page.py", line 278, in captcha_download_links_generator
    captcha_answer = captcha_solve_func(
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\blablabla\AppData\Local\Programs\Python\Python311\Lib\site-packages\uldlib\captcha.py", line 29, in tkinter_user_prompt
    u = requests.get(img_url)
        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\blablabla\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\blablabla\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\blablabla\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\blablabla\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "C:\Users\blablabla\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "C:\Users\blablabla\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 445, in prepare_url
    raise InvalidURL(f"Invalid URL {url!r}: No host supplied")
requests.exceptions.InvalidURL: Invalid URL 'https:https://xapca.uloz.to/196a73d46f8951da0c5cc2930e94d33242087af6/image.jpg': No host supplied
Terminating tor..
Removed tor data dir: tor_data_dir_a0400b05-f053-4267-843a-3a0b3d4ed934

**Comment by setnicka** [comment]
Z jaké verze ulozto-downloaderu to je (`ulozto-downloader --version` to vypíše).

**Comment by cqeta1564** [comment]
C:\Users\blablabla>ulozto-downloader --version
2.6.0
