### ISSUE TITLE
chyba "Unable to start TOR"

### ISSUE THREAD

**Issue by Bob4716** [setnicka/ulozto-downloader#174]
piše my to error:

[TOR]   Unable to start TOR: 'tor' isn't available on your system. Maybe it's not in your PATH?
Terminating download. Please wait for stopping all threads.
Download terminated.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\xxx\AppData\Roaming\Python\Python311\Scripts\ulozto-downloader.exe\__main__.py", line 7, in <module>
  File "C:\Users\xxxx\AppData\Roaming\Python\Python311\site-packages\uldlib\cmd.py", line 143, in run
    d.download(url, args.parts, args.password, args.output, args.temp, args.yes, args.conn_timeout, args.enforce_tor)
  File "C:\Users\xxx\AppData\Roaming\Python\Python311\site-packages\uldlib\downloader.py", line 278, in download
    download_url = next(self.captcha_download_links_generator)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Roaming\Python\Python311\site-packages\uldlib\page.py", line 263, in captcha_download_links_generator
    self.tor.launch()  # ensure that TOR is running
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Roaming\Python\Python311\site-packages\uldlib\torrunner.py", line 60, in launch
    self.start()
  File "C:\Users\xxxj\AppData\Roaming\Python\Python311\site-packages\uldlib\torrunner.py", line 49, in start
    self.tor_process = stem.process.launch_tor_with_config(config=TOR_CONFIG)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxj\AppData\Roaming\Python\Python311\site-packages\stem\process.py", line 296, in launch_tor_with_config
    return launch_tor(tor_cmd, args, torrc_path, completion_percent, init_msg_handler, timeout, take_ownership)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Roaming\Python\Python311\site-packages\stem\process.py", line 103, in launch_tor
    raise OSError("'%s' isn't available on your system. Maybe it's not in your PATH?" % tor_cmd)
OSError: 'tor' isn't available on your system. Maybe it's not in your PATH?

"[TOR]   Unable to start TOR: 'tor' isn't available on your system. Maybe it's not in your PATH?"

přitom ho mam v path

![LwmT](https://github.com/setnicka/ulozto-downloader/assets/96495576/f5fee2cd-c742-4762-aaf4-049b88bc1baf)

nevíte co stým?

**Comment by Bob4716** [comment]
opraveno sem debil stačilo restarnout terminál pak se mi ale další chyba #172 opraveno #173 až na chybu kterou jsem psal v komentech u #173, jinak děkuji za vaši prací.
