### ISSUE TITLE
 Blocked TOR exit IP.. get new TOR session

### ISSUE THREAD

**Issue by xdigitalfoto** [setnicka/ulozto-downloader#182]
Blocked TOR exit IP.. get new TOR session

**Comment by filo891** [comment]
Could you please share a bit more information here? What is the client version you are using? What is the expected and actual behavior you are experiencing? 

This error message is normally not a fatal error and the application shuld simply retry with a new Tor circuit.

**Comment by tex** [comment]
docker: pkejval/uld-docker:main

Traceback (most recent call last):
  File "/app/ulozto-downloader/ulozto-downloader.py", line 7, in <module>
    cmd.run()
  File "/app/ulozto-downloader/uldlib/cmd.py", line 157, in run
    d.download(url, args.parts, args.password, args.output, args.temp, args.yes, args.conn_timeout, args.enforce_tor)
  File "/app/ulozto-downloader/uldlib/downloader.py", line 282, in download
    download_url = next(self.captcha_download_links_generator)
  File "/app/ulozto-downloader/uldlib/page.py", line 335, in captcha_download_links_generator
    r = self.cfsolver.get(self.captchaURL)
  File "/app/ulozto-downloader/uldlib/cfsolver.py", line 177, in get
    return self.request(target, timeout, 'request.get')
  File "/app/ulozto-downloader/uldlib/cfsolver.py", line 172, in request
    raise RuntimeError(f"Cloudflare solver error: {result.get('message')}")
RuntimeError: Cloudflare solver error: Error: Error solving the challenge. Cloudflare has blocked this request. Probably your IP is banned for this site, check in your web browser.
ulozto-downloader is initializing...
Tor: TOR started
Captcha: TOR get new CAPTCHA (timeout 30 sec)
Captcha: TOR get new CAPTCHA (timeout 30 sec)
Captcha: Solving Cloudflare WAF challenge (timeout 90 sec)...
11/03/23 19:53:05 - Done downloading
