### ISSUE TITLE
Requests through Tor blocked by CloudFlare

### ISSUE THREAD

**Issue by filo891** [setnicka/ulozto-downloader#183]
Seems Ulozto is striking back and CloudFlare is no longer only enabling bot protection, but compleely blocking Tor exit IPs.

I'm getting the following error on the Flaresolverr branch:
```
# python3 ulozto-downloader.py --parts-progress https://ulozto.sk/file/piKNXW6z8AA2/debian-11-7-0-amd64-netinst-iso
[Autodetect] tflite_runtime available, using --auto-captcha
Starting downloading for url 'https://ulozto.sk/file/piKNXW6z8AA2/debian-11-7-0-amd64-netinst-iso'
Getting info (filename, filesize, …)
Downloading into: './debian-11.7.0-amd64-netinst.iso'
You are lucky, this is slow direct download without CAPTCHA :)
[TOR]   TOR started
[Link solve]    TOR get downlink (timeout 30 sec)
[Link solve]    Direct download does not seem to work, trying with captcha resolution instead...
[Link solve]    TOR get new CAPTCHA (timeout 30 sec)
Cloudflare WAF still detected, enforcing automated Cloudflare Solver...
[Link solve]    TOR get new CAPTCHA (timeout 30 sec)
[Link solve]    Solving Cloudflare WAF challenge (timeout 90 sec)...
Terminating download. Please wait for stopping all threads.
Download terminated.
Traceback (most recent call last):
  File "/home/user/ulozto-downloader/ulozto-downloader.py", line 7, in <module>
    cmd.run()
  File "/home/user/ulozto-downloader/uldlib/cmd.py", line 157, in run
    d.download(url, args.parts, args.password, args.output, args.temp, args.yes, args.conn_timeout, args.enforce_tor)
  File "/home/user/ulozto-downloader/uldlib/downloader.py", line 282, in download
    download_url = next(self.captcha_download_links_generator)
  File "/home/user/ulozto-downloader/uldlib/page.py", line 335, in captcha_download_links_generator
    r = self.cfsolver.get(self.captchaURL)
  File "/home/user/ulozto-downloader/uldlib/cfsolver.py", line 241, in get
    return self.request(target, timeout, 'request.get')
  File "/home/user/ulozto-downloader/uldlib/cfsolver.py", line 236, in request
    raise RuntimeError(f"Cloudflare solver error: {result.get('message')}")
RuntimeError: Cloudflare solver error: Error: Error solving the challenge. Cloudflare has blocked this request. Probably your IP is banned for this site, check in your web browser.
```

And the view from Tor Browser:
![image](https://github.com/setnicka/ulozto-downloader/assets/5667984/be698723-f9ba-4ae2-b8af-1651c737c8f9)

Is it still working for anybody, or we are done again?

**Comment by zbyna** [comment]
Same issue. I tried [latest version of flaresolver](https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.3.7) without thinking and after failing I got feeling that problem is somewhere else:
![obrazek](https://github.com/setnicka/ulozto-downloader/assets/3373705/68a5cb33-a122-423c-8723-a07ef3ceec2e)

**Comment by Scavy** [comment]
Same problem for me, these last few days.
Tried with both FlareSolver 3.3.6 and 3.3.7.
But it looks more like that all TOR exit node IPs has been blocked.. which would invalidate this project.

Only use I can imagine, is if it is possible to replace tor, with a proxy client and a list of proxies to use. And then be able to use those private proxies to split up the download process over multiple different IPs.

**Comment by Vojtak42** [comment]
It works for me but like this:
![obrazek](https://github.com/setnicka/ulozto-downloader/assets/18753137/0544fe30-6293-4010-af52-34070bf19d67)

**Comment by zbyna** [comment]
[Bridges](https://bridges.torproject.org/) could help to solve ip blocking issue.
[How to obtain bridge](https://bridges.torproject.org/)

**Comment by Ghostman863** [comment]
Bridge is working if tor is blocked by your provider /country. So you will connect to bridge, then to tor and then to website. It will be the same. You must have different ip on end of the tor cycle (free proxy /VPN?). 
But on smartphone I had a error on uloz.to with comment by cloudflare. So uloz.to is using cloudflare for blocking tor ip. Maybe there will be a way to bypass cloudflare service.

**Comment by angorak** [comment]
Do we necessarily need to access it from the tor network ? When I start downloading (from one public IP) the same file with a clear cookies, it lets me download two and then there is a google recaptcha and after that it lets to download the next one.  Wouldn't the google recaptcha solver solve this ?

**Comment by zbyna** [comment]
@Ghostman863 Thanks for clarification! Tor [exit nodes](https://blog.torproject.org/changes-tor-exit-list-service/) are publicly available so it may be “easily” blocked by Cloudflare.This won’t be the way ☹️

**Comment by Ghostman863** [comment]
We could try to use it with proxychain, where we can write a specific free proxy. Then connection will be pc-tor-PROXY-ulozto. With that we can bypass it, but i dont know how it will be work with downloader and changing IP for downloading.
Or in issue (i think #157) setnicka wrote something like as "according to their terms, we dont violate anything". So we can try to contact theme for disable filter, because people from third world countries couldnt used it without tor :D

**Comment by Mikkauser** [comment]
Pekny den, prosim ktory fork momentalne funguje s rychlejsim stahovanim? Niekto v starych vlaknach doporucil pouzit nizsiu verziu, ale tych vlakien je uz tolko, ze naozaj netusim co funguje. je tu velmi vela vlakien :( Diky za pomoc !

**Comment by zbyna** [comment]
Zdravíčko, mně nefunguje ve více vláknech žádná verze. A to ani ta z docker image.  ☹️ Už to ani nezkoušim.

**Comment by Vojtak42** [comment]
Teď už je to asi jedno, ale jak to vlastně dělá jdownloader, že může stahovat více souborů najednou?
