### ISSUE TITLE
multiprocessing na win 10

### ISSUE THREAD

**Issue by muniv11111** [setnicka/ulozto-downloader#33]
```
File "<string>", line 1, in <module>
  File "c:\users\muniv\appdata\local\programs\python\python38-32\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "c:\users\muniv\appdata\local\programs\python\python38-32\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "c:\users\muniv\appdata\local\programs\python\python38-32\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "c:\users\muniv\appdata\local\programs\python\python38-32\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "c:\users\muniv\appdata\local\programs\python\python38-32\lib\runpy.py", line 263, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\users\muniv\appdata\local\programs\python\python38-32\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\users\muniv\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\muniv\AppData\Local\Programs\Python\Python38-32\Scripts\ulozto-downloader", line 40, in <module>
    d.download(args.url, args.parts, args.output)
  File "c:\users\muniv\appdata\local\programs\python\python38-32\lib\site-packages\ulozto_downloader\downloader.py", line 196, in download
    self.captcha_process.start()
  File "c:\users\muniv\appdata\local\programs\python\python38-32\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "c:\users\muniv\appdata\local\programs\python\python38-32\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\users\muniv\appdata\local\programs\python\python38-32\lib\multiprocessing\context.py", line 326, in _Popen
    return Popen(process_obj)
  File "c:\users\muniv\appdata\local\programs\python\python38-32\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "c:\users\muniv\appdata\local\programs\python\python38-32\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "c:\users\muniv\appdata\local\programs\python\python38-32\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
^C
```

asi bude potřeba udělat něco takového, ale jsem na to slabý.. :-)  

viz.: https://stackoverflow.com/questions/60266256/how-to-fix-multiprocessing-problems-in-python-in-windows10

**Comment by setnicka** [comment]
To nevypadá hezky :(

Nemám teď rychle po ruce žádné Win k testu, ale zkusil jsem přesunout věci v main v hlavním skriptu pod `__main__` check a vystřelil verzi 1.5.2. Zkus na ní updatovat (`pip3 install --upgrade ulozto-downloader`) a ozkoušej to prosím znovu.

Pokud to nepomůže, tak si na to zkusím najít čas během týdne a zkusím to zreplikovat na nějakých Windows.

**Comment by muniv11111** [comment]
```
[7;0H[K[34m[Part 1][0m	Waiting for CAPTCHA...[8;0H[K[34m[Part 2][0m	Waiting for CAPTCHA...[9;0H[K[34m[Part 3][0m	Waiting for CAPTCHA...[10;0H[K[34m[Part 4][0m	Waiting for CAPTCHA...Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\muniv\appdata\local\programs\python\python38-32\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "c:\users\muniv\appdata\local\programs\python\python38-32\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: 'Downloader' object has no attribute '__captcha_breaker'
```
`

někde něco nesedí...

**Comment by setnicka** [comment]
No, `Downloader` má určitě metodu `__captcha_breaker`, ale tohle bude nějaká specialita Multiprocessing. Zkusím na to přijít.

**Comment by muniv11111** [comment]
Jinak já mám svou verzi co jsem nějak vyladil v srpnu, funguje i na pornfile a je v jednom py scriptu jak to bylo puvodně.. která používá k řešení captcha webovou aplikaci z herokuapp.. ale ta je asi tajná.. :-) jen jsem na ni přišel v tom srpnu bo to tu někdo zminoval a fiddler na sledování sitoveho provozu mi pomohl ji najít.. už presně nevím jak sem ji objevil a kdo ji provozuje na tom herokuapp.. ale vyhoda je že mi funguje bez tensorflow na serveru bez X... ten tflite co potrebuje tvoje verze k auto-captcha to je další problém co mi nejde na win amd x64 naistalovat.. furt píše neco toto whl není na teto platformě podporováno.. přitom architektura i verze pythonu by měla být srpávná.. takže moje haluz verze je zatím jediné co mi jede na win i na serveru bez X.. ach jo ty windows..

**Comment by Koticka** [comment]
Tak asi jsem přišel na řešení:

https://stackoverflow.com/questions/517970/how-to-clear-the-interpreter-console
V kódu je os.system("clear"), to funguje na linuxu. Na windowsu je cls.

Dále, jak to padá na chybějící attribut __captcha_breaker. Stačilo opravit to na jedno podtržítko. Prefix dvou podtržítek používá python pro nějaké své interní věci, jedno podtržítko se má používat na "privátní" metody atd.

Nakonec, první chybu lze vyřešit nějakým hackem ze SO. ulozto-downloader nemá definovanou main metodu, tak jsem ji vytvořil a nechal ji volat z if __name__ == "__main__" bloku, a funguje.

Vypadá to, že to funguje, vytvořím PR.

**Comment by muniv11111** [comment]
` File "ulozto-downloader", line 47, in <module>
    main()
  File "ulozto-downloader", line 43, in main
    d.download(args.url, args.parts, args.output)
  File "c:\users\muniv\appdata\local\programs\python\python38-32\lib\site-packages\ulozto_downloader\downloader.py", line 236, in download
    p.start()
  File "c:\users\muniv\appdata\local\programs\python\python38-32\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "c:\users\muniv\appdata\local\programs\python\python38-32\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\users\muniv\appdata\local\programs\python\python38-32\lib\multiprocessing\context.py", line 326, in _Popen
    return Popen(process_obj)
  File "c:\users\muniv\appdata\local\programs\python\python38-32\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "c:\users\muniv\appdata\local\programs\python\python38-32\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'weakref' object
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\muniv\appdata\local\programs\python\python38-32\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "c:\users\muniv\appdata\local\programs\python\python38-32\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
`

tak nevím mne to pořád nejede, na začátku to hodilo tohle, pak to sice po minutě chce pokažré třikrát  zadat captcha, ale nesputí se ani jedno stahování, už to běží asi 10 minut... jedu teda bez tensorflow bo ten mi proste nejde z neznámých duvodu na win naistalovat.. na linux to šlo bez problémů..

**Comment by Koticka** [comment]
@muniv11111  U mě to jede, zkusil jsem to na verzi Python 3.6.8.

Zkoušíš správnou verzi (není to zamergované)? Zkusil jsi vytvořit nový environment? Máš 64-bit windows? Co má za problém ten Tensorflow Lite Interpreter při instalaci? Máš chybovou hlášku?

**Comment by muniv11111** [comment]
ten tensorflow hází:
.whl is not supported wheel on this platform.. mám Quad-core AMD Ryzen 5 r5-3550h processor Windows 10 64-bit.. nevím jsem z toho jelen.. dával jsem tohle istalovat: https://github.com/google-coral/pycoral/releases/download/release-frogfish/tflite_runtime-2.5.0-cp38-cp38-win_amd64.whl

**Comment by Koticka** [comment]
@muniv11111 Aby ti jelo tensorflow, tak potřebuješ mít Python 64-bitů myslím.

**Comment by Koticka** [comment]
@muniv11111 Mohl bys to zkusit na Pythonu 3.6? Toto bude na dlouho.

Je tam asi problém s picklením při startování procesu. Bohužel nevidím teď jednoduchý způsob, jak toto vyřešit.

**Comment by Koticka** [comment]
@setnicka Tak problém spočíval v picklení funkcí při vytváření procesů, na verzi 3.8 windows s tím je z nějakého důvodu problém. Změnil jsem některé funkce, co nepotřebovaly self, na static, a vyřešilo se to tím.

**Comment by muniv11111** [comment]
@Koticka Na to self jsem dokonce koukal než jsem sem hodil issue, že to v té mé haluz verzi co jede nemám.. ale nevěděl jsem už cos s tím dál... :-) otestuju co nejdřív a dám vědět...

**Comment by Koticka** [comment]
@muniv11111 Díky. Něco jsem tam ještě upravil, možná to pomůže. Mohl bys to otestovat u sebe? U mě na windowsu to jede.

**Comment by muniv11111** [comment]
@Koticka supr jede -  jak bez tensorflow na python 3.8 32 bit tak i s tensorflow na python 3.8 64bitové verzi s auto-captcha zkoušeno opět na 15 parts debian-9.6.0-amd64-netinst.iso, staženo cca za 5 minut takže cca třikrát rychleji než obvykle a to je ted špička doma.. :-)

**Comment by sinepgnol** [comment]
Zdravim, tak bohuzial u mna stale ta ista chyba. Mam najnovsiu verziu ulozto-downloadera, skusal som aj upgrade podla prikazu `pip3 install --upgrade ulozto-downloaderpip3 install --upgrade ulozto-downloader`.
Ficim na macOS s pythonom 3.8.5.
`% ulozto-downloader --output /Volumes/moje\ data/Walovi\ filky --auto-captcha https://pornfile.cz/file/ncxjrSfhn/romky-a-jejich-videa-47-mp4
Starting downloading for url 'https://pornfile.cz/file/ncxjrSfhn/romky-a-jejich-videa-47-mp4'
Getting info (filename, filesize, ...)
CAPTCHA protected download - CAPTCHA challenges will be displayed

[ignored] torpy.documents.network_status.FetchDescriptorError: Can't fetch descriptor from http://95.211.118.194:7003/tor/server/fp/49FE0485D1D958CE0024D06AA4CB99E84A6DAD22
[CAPTCHA solve]	CAPTCHA auto solved as 'atgz'
File:		Romky a jejich videa (47).mp4
URL:		https://pornfile.cz/file/ncxjrSfhn/romky-a-jejich-videa-47-mp4
Download type:	CAPTCHA protected download
Total size:	565.3MB
Parts:		10 x 56.53MB

[Part 1]	Waiting for CAPTCHA...
[Part 2]	Waiting for CAPTCHA...
[Part 3]	Waiting for CAPTCHA...
[Part 4]	Waiting for CAPTCHA...
[Part 5]	Waiting for CAPTCHA...
[Part 6]	Waiting for CAPTCHA...
[Part 7]	Waiting for CAPTCHA...
[Part 8]	Waiting for CAPTCHA...
[Part 9]	Waiting for CAPTCHA...
[Part 10]	Waiting for CAPTCHA...Traceback (most recent call last):
  File "/Users/Martin/.pyenv/versions/3.8.5/bin/ulozto-downloader", line 48, in <module>
    main()
  File "/Users/Martin/.pyenv/versions/3.8.5/bin/ulozto-downloader", line 44, in main
    d.download(args.url, args.parts, args.output)
  File "/Users/Martin/.pyenv/versions/3.8.5/lib/python3.8/site-packages/ulozto_downloader/downloader.py", line 209, in download
    self.captcha_process.start()
  File "/Users/Martin/.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/Martin/.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/Martin/.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/Martin/.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/Martin/.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/Martin/.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/Martin/.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'generator' object

`

**Comment by raptorxcz** [comment]
Já mám podobnou chybu a taky z macOS:

```Download type:	CAPTCHA protected download
Size / parts: 	1850.78MB => 10 x 185.08MB
[Part 0]	Waiting for CAPTCHA...
[Part 1]	Waiting for CAPTCHA...
[Part 2]	Waiting for CAPTCHA...
[Part 3]	Waiting for CAPTCHA...
[Part 4]	Waiting for CAPTCHA...
[Part 5]	Waiting for CAPTCHA...
[Part 6]	Waiting for CAPTCHA...
[Part 7]	Waiting for CAPTCHA...
[Part 8]	Waiting for CAPTCHA...
[Part 9]	Waiting for CAPTCHA...Traceback (most recent call last):
  File "/usr/local/bin/ulozto-downloader", line 8, in <module>
[Progress]	 0.00 MB (0.00 %)	avg. speed: 0.00 MB/s	curr. speed: 0.00 MB/s	remaining: 0:00:00
  File "/usr/local/lib/python3.9/site-packages/uldlib/cmd.py", line 44, in run
    d.download(args.url, args.parts, args.output)
  File "/usr/local/lib/python3.9/site-packages/uldlib/downloader.py", line 306, in download
    self.captcha_process.start()
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'weakref' object

```

Python 3.9.6
