### ISSUE TITLE
Nefunguje na termux

### ISSUE THREAD

**Issue by Vojtak42** [setnicka/ulozto-downloader#60]
Prosím opravit, aby fungoval program na termux pro android. Našel jsem, že se chyba vyskytovala i v jiných projektech a opravili ji.

Error:
File:           Stargate Empire at War rozbal a hraj.rar
URL:            https://ulozto.cz/file/FUtC4j0FUdNW/stargate-empire-at-war-rozbal-a-hraj-rar
Download type:  slow direct download (without CAPTCHA)
[Part 0]        Waiting for direct link...
[Part 1]        Waiting for direct link...Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.9/lib-dynload/_multiprocessing.cpython-39.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/ulozto-downloader", line 8, in <module>
    sys.exit(run())
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/uldlib/cmd.py", line 44, in run                 d.download(args.url, args.parts, args.output)         File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/uldlib/downloader.py", line 272, in download
    self.download_url_queue = mp.Queue(maxsize=0)         File "/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/context.py", line 103, in Queue
    return Queue(maxsize, ctx=self.get_context())         File "/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/queues.py", line 40, in __init__
    from .synchronize import SEM_VALUE_MAX as maxsize
  File "/data/data/com.termux/files/usr/lib/python3.9/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.

**Comment by Vojtak42** [comment]
Vyřešeno zde: #78 # # a [zde](https://wiki.termux.com/wiki/Graphical_Environment) tkinter
