### ISSUE TITLE
Nevím...

### ISSUE THREAD

**Issue by muniv11111** [setnicka/ulozto-downloader#69]
./python3.7 ./ulozto-downloader --auto-captcha --parts 24 https://uloz.to/file/4bSHbFIpNeDQ/hovorme-spolu-live-stream-ii-cast-2-28-11-2021-od-9-00-do-22-00-mp4
Starting downloading for url 'https://uloz.to/file/4bSHbFIpNeDQ/hovorme-spolu-live-stream-ii-cast-2-28-11-2021-od-9-00-do-22-00-mp4'
Getting info (filename, filesize, ...)
You are lucky, this is slow direct download without CAPTCHA :)
Starting TOR...
Traceback (most recent call last):new TOR connection: Connection error, try new TOR session.
  File "/home24/muniv/opt/python-3.7.9/lib/python3.7/site-packages/stem/socket.py", line 535, in _make_socket
    control_socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./ulozto-downloader", line 8, in <module>
    sys.exit(run())
  File "/home24/muniv/opt/python-3.7.9/lib/python3.7/site-packages/uldlib/cmd.py", line 44, in run
    d.download(args.url, args.parts, args.output)
  File "/home24/muniv/opt/python-3.7.9/lib/python3.7/site-packages/uldlib/downloader.py", line 237, in download
    download_url = next(self.captcha_download_links_generator)
  File "/home24/muniv/opt/python-3.7.9/lib/python3.7/site-packages/uldlib/page.py", line 240, in captcha_download_links_generator
    self.tor.reload()
  File "/home24/muniv/opt/python-3.7.9/lib/python3.7/site-packages/uldlib/torrunner.py", line 72, in reload
    self.ctrl = Controller.from_port(port=self.tor_ports[1])
  File "/home24/muniv/opt/python-3.7.9/lib/python3.7/site-packages/stem/control.py", line 1033, in from_port
    control_port = stem.socket.ControlPort(address, port)
  File "/home24/muniv/opt/python-3.7.9/lib/python3.7/site-packages/stem/socket.py", line 503, in __init__
    self.connect()
  File "/home24/muniv/opt/python-3.7.9/lib/python3.7/site-packages/stem/socket.py", line 172, in connect
    self._socket = self._make_socket()
  File "/home24/muniv/opt/python-3.7.9/lib/python3.7/site-packages/stem/socket.py", line 538, in _make_socket
    raise stem.SocketError(exc)
stem.SocketError: [Errno 111] Connection refused
Terminating tor..
Removed tor data dir: tor_data_dir_900ce20b-da1e-45f4-a3de-0a01be1e4543

**Comment by setnicka** [comment]
Zavírám starou issue. Pravděpodobně problém s tím, že Tor nezvládl vytvořit spojení s Tor sítí.
