### ISSUE TITLE
Chyba - nelze stahovat

### ISSUE THREAD

**Issue by Marikoscz** [setnicka/ulozto-downloader#91]
Zdravím, po nějaké době jsem chtěl spustit stahování, ovšem objevila se následující chyba a já nevím, co s tím.
Používám Linux Ubuntu 20.04.4 LTS

Starting TOR...
Traceback (most recent call last):HA
  File "/usr/local/bin/ulozto-downloader", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.8/dist-packages/uldlib/cmd.py", line 44, in run
    d.download(args.url, args.parts, args.output)
  File "/usr/local/lib/python3.8/dist-packages/uldlib/downloader.py", line 237, in download
    download_url = next(self.captcha_download_links_generator)
  File "/usr/local/lib/python3.8/dist-packages/uldlib/page.py", line 278, in captcha_download_links_generator
    captcha_answer = captcha_solve_func(
  File "/usr/local/lib/python3.8/dist-packages/uldlib/captcha.py", line 94, in __call__
    u = requests.get(img_url)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 452, in prepare_request
    p.prepare(
  File "/usr/lib/python3/dist-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 390, in prepare_url
    raise InvalidURL("Invalid URL %r: No host supplied" % url)

**Comment by Marikoscz** [comment]
Po prohledání issues jsem zjistil, že je chyba pravděpodobně v  InvalidURL("Invalid URL %r: No host supplied" % url), tedy v CAPTCHI a URL adresy ze které se CAPTCHA čte. Bohužel ale mám problém v Linuxu najít soubor, nebo tedy soubor jsem našel, ale konkrétní parametr, nebo podmínku, kterou mám upravit jsem nenašel.
Budu moc rád, kdyby mi někdo poradil, klidně i radou jak pro blbečky, i tak budu moc rád.

**Comment by Marikoscz** [comment]
Chyba vyřešena přepsáním **_page.py_**
[fix](https://github.com/Vojtak42/ulozto-downloader/commit/c611199c503e885bb39471984281d5d6889cad41)
Funguje opět perfektně

PS: Na linuxu jsem našel page.py v cestě _/home/username/.local/lib/python3.8/site-packages/uldlib_ (pro případ, že by jej někdo, jako já, nemohl najít)

**Comment by Pheggas** [comment]
Díky. Toto musí byť definitívne mergnuté ASAP. Mohol si nechať túto issue otvorenú aby si to dev všimol resp. nahoď pull request.

**Comment by setnicka** [comment]
Tenhle fix je už dlouho mergnutý v master verzi, viz commit https://github.com/setnicka/ulozto-downloader/commit/8d8680be7198bbac6dee4ef1bf566a30daf1e282 (vydáno ve verzi 3.0.0 a novějších).

**Comment by Pheggas** [comment]
Aha, sorry. Očividne mám staršiu verziu tak som editoval page.py manuálne.
