### ISSUE TITLE
Hello. Can't get past this. Any help is welcome.

### ISSUE THREAD

**Issue by Ferathor** [setnicka/ulozto-downloader#95]
Getting info (filename, filesize, ...)
CAPTCHA protected download - CAPTCHA challenges will be displayed

Starting TOR...
Traceback (most recent call last):HA
  File "/usr/local/bin/ulozto-downloader", line 11, in <module>
    load_entry_point('ulozto-downloader==2.6.0', 'console_scripts', 'ulozto-downloader')()
  File "/usr/local/lib/python3.7/dist-packages/uldlib/cmd.py", line 44, in run
    d.download(args.url, args.parts, args.output)
  File "/usr/local/lib/python3.7/dist-packages/uldlib/downloader.py", line 237, in download
    download_url = next(self.captcha_download_links_generator)
  File "/usr/local/lib/python3.7/dist-packages/uldlib/page.py", line 279, in captcha_download_links_generator
    "https:" + captcha_image_url, print_func=print_func)
  File "/usr/local/lib/python3.7/dist-packages/uldlib/captcha.py", line 94, in __call__
    u = requests.get(img_url)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 640, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 731, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'https:https://xapca.uloz.to/f0a78510453d571d2df06b445b66c35f3f6196fa/image.jpg'
Terminating tor..
Removed tor data dir: tor_data_dir_0ac95326-884a-4057-8f3c-b4d0f9cf64f6

**Comment by zbyna** [comment]
It seems that this issue was [fixed](https://github.com/setnicka/ulozto-downloader/issues/82), but a new version has not been published in PyPI yet. As a temporary solution please try: `pip install git+https://github.com/zbyna/ulozto-downloader.git@fix#82-multiprocessingdummy#egg=ulozto-downloader `

**Comment by setnicka** [comment]
Published to PyPI as a version [3.0.0](https://pypi.org/project/ulozto-downloader/3.0.0/). Should be fixed now.
